### ISSUE TITLE
[Help]: iOS app crashes when disconnecting from Raspberry Pi's Bluetooth connection

### ISSUE THREAD

**Issue by SevenCho** [chipweinberger/flutter_blue_plus#1161]
### Requirements

- [x] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.35.3 

### Flutter Version

3.27.1

### What OS?

iOS

### OS Version

iOS 15.7 / 18.3.2

### Bluetooth Module

OrangePi 20U5622

### What is your problem?

It works fine with versions 1.33.6 and earlier. 
With later versions, the app crashes when Bluetooth is disconnected, and the stack trace shows that -[CBService invalidate] is called continuously until the app crashes.

<img width="1361" alt="Image" src="https://github.com/user-attachments/assets/7107bf87-fdf3-499e-86da-105ec197d998" />

### Logs

```shell
[FBP-iOS] handleMethodCall: stopScan
flutter: [FBP] \^[[1;30m(stopScan)\^[[0m result: \^[[1;33mtr<…>
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x16d7cfff0)
    frame #0: 0x00000001afb56f50 CoreBluetooth`-[CBService invalidate] + 8
CoreBluetooth`-[CBService invalidate]:
->  0x1afb56f50 <+8>:  stp    x28, x27, [sp, #0x190]
    0x1afb56f54 <+12>: stp    x26, x25, [sp, #0x1a0]
    0x1afb56f58 <+16>: stp    x24, x23, [sp, #0x1b0]
    0x1afb56f5c <+20>: stp    x22, x21, [sp, #0x1c0]
Target 0: (Runner) stopped.
```

**Comment by chipweinberger** [comment]
can you please find the specific commit that broke it?

```
dependencies:
  flutter_blue_plus:
    git:
      url: https://github.com/chipweinberger/flutter_blue_plus.git
      ref: a1b2c3d4e5f6g7h8i9j0  # replace with your commit hash
```

and then ideally find the specific line and open a PR. Thanks
